require('dotenv').config()
const { WebClient } = require('@slack/web-api');
const options = {};
const web = new WebClient(process.env.SLACK_TOKEN, options);

console.log('🚀 Slack Notifier 🚀');

export const  authTest = async () => {
    console.log('Testing authentication...');
    console.log(process.env.SLACK_TOKEN);
    try {
      const result = await web.auth.test();
      console.log('Authentication successful:', result);
    } catch (error) {
      console.error('Authentication failed:', error);
    }
  }



export const sendMessage = async (message, channel = null) => {
    const channelId = channel || process.env.SLACK_CHANNEL_ID;

    console.log("channelId", channelId);
    // Join the channel
    try {
        console.log(process.env.SLACK_TOKEN);
        const resp = await web.conversations.join({
            channel: channelId,
        });
        if (resp.ok) {
            console.log(`Successfully joined channel: ${channelId}`);
        } else {
            console.log(`Failed to join channel: ${response.error}`);
        }
    } catch (error) {
        console.log("Error", error);
    }

    // Send the message
    try {
        const result = await web.chat.postMessage({
            channel: channelId,
            text: message,
        });
        console.log('Message sent:', result.ts);
    } catch (error) {
        console.error('Error posting message:', error);
    }
};

authTest()
sendMessage('This is generated by Notifier Test App')
